pypiserver/pypiserver

pypiserver/core.py

In case the package repository contains several file types, the
server exposes all by default. For instance, it exposes html files
as package files...

Check if a file is a proper package before showing it

---

pypiserver/_app.py

We run an internal pypi server and have both sdists and wheels on it.  When refreshing they reorder because the sort only sorts on version number.  This change makes that sort more deterministic.

More deterministic sort of packages

---

pypiserver/core.py
tests/test_core.py

Fixes package name and package version handling of bdist_dumb
packages
Detects OS name boundary as specified in
http://svn.python.org/projects/python/trunk/Lib/distutils/util.py
Also detects cpN and pyN boundary
fixes #88, connected to #88

Incorrect package name detection with OSX version scheme #88

---

README.rst
pypiserver/_app.py
pypiserver/cache.py
pypiserver/core.py
pypiserver/manage.py
setup.py
tests/test_manage.py

pypiserver has worked great for us over the last 2 years, but over time we've accumulated 25000 individual package files (mostly artifacts from automatic builds) and pypiserver has really slowed down for us.
This PR adds some significant optimizations for this particular use case -- in particular, it holds the list of packages in memory so we don't have to scan all 25000 packages each time pip queries the server (which is a few times per package). It uses the `watchdog` package to invalidate the cache, and will not activate the cache if it is not installed.
Another significant speedup we found was using an nginx proxy, and adding the following to make nginx serve the packages directly by pointing the `/packages/` location to its parent directory:
```
location /packages/ {
root …
```

Serve tens of thousands of packages efficiently

---

README.rst

The documentation in `README.rst` for running pypiserver via gunicorn uses an example with positional arguments to pypiserver:app(), however this throws errors:
$ gunicorn --error-logfile=- 'pypiserver:app("/var/build/wheels")'
<snip>
Traceback (most recent call last):
File "/opt/pypiserver/1.1.10/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
worker.init_process()
File "/opt/pypiserver/1.1.10/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
self.load_wsgi()
File "/opt/pypiserver/1.1.10/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
self.wsgi = self.app.wsgi()
File "/opt/pypiserver/1.1.10/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = …

Fix documentation for starting pypiserver with gunicorn

---

README.rst
requirements/dev.pip
setup.py

Issue #120 showed that passlib>=1.6 is required for proper functioning of package uploads. The `passlib` extra now explicitly requires this.
Also includes a small PEP 008 whitespace change in line 18 of `setup.py`.

Added passlib version specification (#120)

---

README.rst

Fix typo, the package name in pypi is pypiserver and not pypi-server.

Fix typo, the package name is pypiserver

---

pypiserver/__init__.py
tests/test_init.py

Incorporated changes from @ankostis PR #127 and added a test that fails on current master with the same error message as in #124, but succeeds with changed code.
Test fails with the following error message, as seen in #124:
````
(Python35)[Nautilus@Nautilus-2 pypiserver]$ py.test tests/test_init.py 
====================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.5.0, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /Users/Nautilus/Documents/Programming/ihiji/pypiserver, inifile: tox.ini
plugins: cov-2.2.1
collected 3 items 
tests/test_init.py FFF
=========================================================================================== …
```

FIX #124: Convert forgotten attr-access-->dict-access.

---

tests/test_app.py

My result appears different than the expected outcome.
Using an `ubuntu/trusty` docker container as a build/test environment the uploaded `asc` file gets listed first. For all intents, the order of the result doesn't matter to me.
An improvement to this could be the comparison of sorted sets, but I didn't think of that until just now.

test_upload_with_signature fix to allow uploaded files in any order.

---

tests/test_server.py

Test suite hangs because an upload test prompts for a user-supplied password. This PR uses the pypirc context manager to supply a default password.
See:
https://travis-ci.org/pypiserver/pypiserver/builds/129511699
https://travis-ci.org/pypiserver/pypiserver/builds/126811063
https://travis-ci.org/pypiserver/pypiserver/builds/128599164
https://travis-ci.org/pypiserver/pypiserver/builds/130325284

upload test requires pypirc to avoid password prompt

---

pypiserver/_app.py
pypiserver/core.py
tests/test_app.py

PEP 503 addresses #139 (and also #38, which was I believe actual motivation of the PEP...) .
This PR makes the following changes to bring pypiserver up to spec:
- URLs are redirected unless they end in `/` (expect packages themselves).
- Package names are normalized: lowercase with all runs of the characters `.` , `-` , or `_` replaced with a single `-` character.
- The simple index only lists normalized package names.
- Any request for a non-normalized package name is redirected to the normalized name.
Note that pip >=8.1.2 will only request normalized package names. Apparently this change was intended to be in 8.0.0, but an implementation bug did not apply normalization correctly so that packages with dots (`.`) were requested unnormalized.
Tests added / updated.

PEP 503 Package Name Normalization and URL Redirects

---

README.rst
pypiserver/_app.py
pypiserver/cache.py
pypiserver/core.py

Turns out, those file digests get really annoying if you have a hundred or so packages that are 40mb each (don't ask... ). This improves the cache and makes that less annoying.

Add a separate cache for file digests

---

pypiserver/__main__.py
pypiserver/manage.py

* import xmlrpclib.ServerProxy as replace for Server in Python2.7
* `update_directory = None,` syntax result in a tuple but None and this code poisons the `update` function in `manage.py`

two fix for issue #129

---

pypiserver/__init__.py

This is a rebased version of #156, which reads:
----
Here's an example paste.ini:
```
[composite:main]
use = egg:Paste#urlmap
/pypi/ = pypiserver
[app:pypiserver]
use = egg:pypiserver#main
root = %(here)s/packages
authenticated = list update download
redirect_to_fallback = False
password_file = %(here)s/htpasswd.txt
log_file = %(here)s/log.txt
verbosity = 2
[server:main]
use = egg:gunicorn#main
host = 127.0.0.1
port = 8001
workers = 4
accesslog = %(here)s/accesslog.txt
```
The following configuration keywords were not being propagated into the app:
```
authenticated = list update download
password_file = %(here)s/htpasswd.txt
log_file = %(here)s/log.txt
verbosity = 2
```
Now it works.
Hope you like the code.
I tried to keep same style.

propagate configuration from paste.ini

---

README.rst

Resolves some inconsistencies and inaccuracies in the docs as
pointed out by @mforkel in #170 
* Fixed endpoint for search example
* Noted the lack of a `/simple` endpoint for search
* Added `search` to the list of explicitly enumerated
functionality in `Known Limitations`

Update Search Documentation

---

pypiserver/__init__.py
tests/test_init.py

This brings back the import hack that allows one to use Paste urlmap to
compose multipe PyPi servers within a single WSGI server.
After importing _app, we remove it from sys.modules so that future
imports will have their own copy, this allows globals to function
correctly and each _app to have their own variables.
Closes: https://github.com/pypiserver/pypiserver/issues/167

Allow creating multiple servers using Paste

---

.gitignore
.travis.yml
README.rst
bin/gen-standalone.sh
pypiserver/__main__.py
pypiserver/core.py
pypiserver/welcome.html
tests/test_app.py
tests/test_main.py

`pypi.python.org/simple` will respond to HTTP requests with `403: SSL is required.`
This will change the default fallback_url to use HTTPS.  This should fix #179.

Default fallback_url to use HTTPS

---

bin/README.rst
bin/bumpver.py
bin/commit-standalone.sh
bin/gen-standalone.sh
bin/package.sh
requirements/dev.pip

A python script to facilitate developers build new releases easily.
You may receive help by executing `./bin/bumpver.py --help`.

feat(build): add `/bin/bumpver.py` script to facilitate new releases

---

README.rst

Adding `X-Forwarded-Proto` makes bottle pick up on the original request's scheme (https/http), so that the URL on the welcome page is displayed correctly.

Add $scheme forwarding to example nginx configuration

---

CHANGES.rst
README.rst
pypiserver/__init__.py

Noticed that I hadn't removed the changelog section about matrix authorization, and went ahead and popped the version up to 1.2.2dev0

Release Tidying

---

pypiserver/__init__.py
tests/test_init.py

Resolves #125 
The ability to propagate configuration values from a paste config
file was introduced in #156. However, as pointed out in #125
by @redbaron4, the string strip method introduced in #156 was
problematic in Python 2.
This resolves that issue while also creating a test that fails
on the current master and passes with updates, demonstrating the
issue.

Resolved paste config parsing issue for Python 2

---

.travis.yml
requirements/dev.pip
tox.ini

Resolves #203
Related to pypa/twine#314
This commit adds an ``sh -c`` call, whose argument is the value of the
environment variable ``PYPISERVER_SETUP_CMD``, or ``true`` if that
variable is not set. This was specifically added to enable the
``pre_twine`` environment, which is provided to automatically test
pre-releases of twine, both for our use (e.g. #203) and for the use of
the twine maintainers (pypa/twine#314).
The capacity to specify an arbitrary setup command via an environment
variable may also wind up being useful in other cases in the future.
In addition, the envlist is updated to include only Python versions we
actually support.
This commit also alphabetizes the ``dev.pip`` requirements and rmeoves
specific requirements for testing using Python 2.5 (which we do not test
against …

Provide Prerelease Testing for Twine

---

.gitignore
CHANGES.rst
README.rst
bin/gen-standalone.sh
pypiserver/__main__.py
pypiserver/core.py
pypiserver/manage.py
pypiserver/welcome.html
tests/test_app.py
tests/test_main.py
tests/test_server.py

Resolves #205 - pypi.python.org shutting down
* Updated the default fallback URL to `pypi.org/simple` rather than
`pypi.python.org/simple`
* Scrubbed references and links to `pypi.python.org`
* Fixed tests breaking due to the removal of `pip.main()` in pip 10.0 -
see pypa/pip#5080 for more info

FIX: Fallback URL, remove calls to pip.main

---

README.rst
bootstrap.py
pypiserver/__main__.py
pypiserver/_app.py
pypiserver/bottle.py
pypiserver/cache.py
pypiserver/core.py
requirements/dev.pip
setup.py
tests/test_app.py
tests/test_init.py

Fix #192.
Also remove some redundant code for Python < 2.7 and 3.0-3.2, and some minor tidy-ups.

Drop support for EOL Python 3.3

---

buildout.cfg

Probably no one is using this, since it hasn't been updated in five years, but even if they are, there's no reason to be using five year old version of packages. Removed the `[versions]` config section.
I've never used buildout, but this seems to be okay according to [their docs](http://www.buildout.org/en/latest/getting-started.html)

Remove version pins from buildout.cfg

---

requirements/dev.pip
tests/test_server.py

Resolves #226
Cleaned up `test_server.py` a bit:
* Call `twine` via `Popen` instead of using their internal API, which
should help us from having to fix twine tests as often
* Cleaned up fixtures
* Some PEP8 updates and general formatting
* Grouped test fixtures and functions all before the tests themselves

test_server.py cleanup

---

pypiserver/_app.py
pypiserver/core.py
tests/doubles.py
tests/test_app.py
tests/test_core.py
tests/test_server.py

Resolves #237
Previously, we were not running any sort of URL escaping on values
passed in from the client that were used for redirects. This allowed
injection attacks via URL encoded newlines in the original request.
This update ensures that all user-supplied paths that are used as
components of redirects are passed through `urllib.parse.quote()`
(or the python 2 equivalent) prior to being used in a redirect
response.
Also specified 127.0.0.1 rather than 0.0.0.0 (the default) in server
tests to avoid triggering firewall dialogs when testing on MacOS

CRLF Injection Mitigation

---

README.rst

Resolves #241
@willrogers points out that `pypiuploader` appears to be a dead project,
so we'll remove specific instructions for it in the docs, unless it
is confirmed to be otherwise.

Remove pypiuploader instructions

---

CHANGES.rst
README.rst
docker-compose.yml
pypiserver/__init__.py

- ENH: pypiserver now consistently and correctly handles the `X-Forwarded-Host`
header to allow for alternative base URLs (#248, resolves #155, thanks
@kujyp for an excellent first-time contribution!)
- DOC: significantly more information added to the `docker-compose.yml`
example, including recipes for various configuration options (thanks
@jetheurer for pointing out the errors in the existing docs, #243!)
- DOC: removed outdated suggestion to serve the packages data directly via
a webserver and replaced with information about setting up nginx
caching (thanks @RiceKab for bringing the issue to our attention, #232)
Resolves #232

REL: 1.3.0

---

pypiserver/cache.py
pypiserver/core.py
tests/test_app.py
tests/test_core.py
tests/test_server.py

@ArneBachmann reported in #265 that SHA256 hashed packages could not be downloaded with pip. From all of the investigation I was able to do, it seems like this has probably been a problem for ~4 years.
I confirmed the bug existed all the way back with pip 8.0, so it's not likely that the pip interface changed out from under us.
Anyway, I updated our method of getting hashes for files to return the full hash, which is what pip expects, rather than a truncated version.
I also resolved a few deprecation warnings in the test suite.

[#265] Resolve issue with non-md5 hashing algorithms

---

pypiserver/__main__.py

This PR will correct a bug that affects the parsing of the `-h` command-line argument, which is the short version of the `--help` argument to print the help message.
Currently the command-line argument `-h` raises this error:
> $ pypi-server -h
> Error: while trying to list root(C:\Users\maggyero\packages): [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\maggyero\\packages'
This is because the `-h` argument was intercepted by a preceding incorrect `elif` clause:
> elif k in "--hash-algo":  # incorrect, should be: elif k == "--hash-algo:"
> [...]
> elif k in ("-h", "--help"):

Correct a command-line argument parsing bug

---

CHANGES.rst
pypiserver/_app.py
tests/test_app.py

Reported by @esciara in #268.
Previously, the `remove_pkg` command was only removing the first
matching package that it found so if, for example, there were a .tar.gz
file and a .whl file, it would only remove one of them.
Of course, it could be run in succession to accomplish full removal, but
the expected behavior is that removal will remove the package entirely.
Here, I've grouped `remove_pkg` related tests into a test class, added
some tests that verify the expected behavior, and updated the
`remove_pkg` method to remove all matching packages.

[268] Ensure remove_pkg removes all pkg instances

---

.travis.yml

I didn't realize GitLab does not support running PRs on forks for
mirrored GitHub repos. I have switched other projects to Azure
pipelines, but just to get things going, I'm going to pull .travis.yml
back in here.

Pull .travis.yml back into repo

---

Dockerfile
docker-requirements.txt

Closes #281
The resulting image should work the same way as the previous Python 2 based one.
I based the Docker image on `python:3.6-alpine` because I believe it is cleaner to use the official Python image for dockerized Python apps, however it comes at the cost of a larger image (~100M). Tell me if it's a problem and I'll find a fix.
I do not think it is possible to be as small as the Python 2 based image though, because Python seems to get slightly bigger at each release.
Using 3.7 or even 3.8 instead is just a matter of replacing the `FROM` statement, but I do not know if you support them yet so I played it safe.
Hope you will find this PR useful !

Use python 3.6 for the Dockerfile

---

.gitlab-ci.yml

The gitlab tests started failing with GL's newest "docker in docker"
image due to the lack of some core C library headers. This ensures that
everything needed for twine (i.e. cryptography) is present before doing
a pip install for twine.

FIX: requirements for docker tests in gitlab

---

pypiserver/_app.py

A couple cases where the error message provided to HTTPError is given format args separately rather than applying the formatting directly. This results in error messages for the user like this, where the package is not shown:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head>
<title>Error: 409 Conflict</title>
<style type="text/css">
html {background-color: #eee; font-family: sans-serif;}
body {background-color: #fff; border: 1px solid #ddd;
padding: 15px; margin: 15px;}
pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
</style>
</head>
<body>
<h1>Error: 409 Conflict</h1>
<p>Sorry, the requested URL <tt>&#039;http://pypiserver/&#039;</tt>
caused an error:</p>
<pre>Package %r already exists!
You may start server with `--overwrite` option.</pre>
</body> …

Fix usage of string formatting in HTTPError

---

README.rst

- Added detailed steps in how to run pypiserver as a service in Windows OS.
Quick and simple patch. I've tested in my local environment and it works great!
Server machine:
Installing packages from a remote machine:

Added running as a service in windows with NSSM to readme

---

pypiserver/bottle.py

CherryPy changed the import location in recent versions.
This attempts the new or falls back to the old location.

Fix CherryPyWSGIServer import

---

docker-requirements.txt

Include watchdog as a dependency in the docker image pip requirements.
This is very useful in situations where your packages are mounted over
the network which may be a typical use case for the image.
As passlib is included as a default dependency this seems like a natural
addition.
---
Have built an image with this configuration which I'm using in Azure with
Azure's File Shares and it lead to a huge performance improvement on
even quite a small (< 100) number of packages.

Include watchdog for cache in Docker image

---

Dockerfile
entrypoint.sh

This PR udpates the Dockerfile.
Docker base images are updated.
The main change is the introduction of an `entrypoint` script, which sets the permission on the package directry `/data/packages`.
In the previous version of the `Dockerfile` this was done before declaring the same directory as docker `VOLUME`, which switched ownership back to `root`.
This behaviour caused: https://github.com/pypiserver/pypiserver/issues/309
To still run `pypiserver` as user and not `root`, the tool `su-exec` was introduced and used within `entrypoint.sh`.

Update Dockerfile. Update docker base images.

---

README.rst
pypiserver/__init__.py
pypiserver/config.py
tests/test_config.py

Thanks @elfjes for pointing out that I'd missed this! I also went ahead
and bumped the version in the README to 2.0.0dev1, so that it's clear
that what's in master shouldn't be what people expect from pypi or in the
docker image.

Restore ability to drop hashing in new config

---

pypiserver/__init__.py
pypiserver/__main__.py
pypiserver/_app.py
pypiserver/config.py
pypiserver/core.py
pypiserver/manage.py
setup.cfg
setup.py
tests/test_app.py
tests/test_config.py
tests/test_core.py
tests/test_init.py
tests/test_main.py
tests/test_manage.py
tests/test_server.py
tox.ini

This PR is a pretty substantial refactor of the entrypoints of pypiserver (`__main__` and `__init__`) to use the argparse-based config added in #339.
- Updated `RunConfig` and `UpdateConfig` classes to have exclusive init kwargs, instead of taking an namespace. This turned out to be much easier when working with the library-style app initialization in `__init__`, both for direct instantiation and via paste config
- Added an `iter_packages()` method to the `RunConfig` to iterate over packages specified by the configuration (note @elfjes, I think that replacing this with e.g. a `backend` reference will be a nice way to tie in #348)
- Added a general-purpose method to map legacy keyword arguments to the `app()` and `paste_app_factory()` functions to updated forms
- Refactored the …

Use argparse config throughout app

---

.travis.yml
tox.ini

~Unfortunately travis doesn't yet have 3.9 (just 3.9-dev2)~ (update: according to [this](https://travis-ci.community/t/python-3-9-0-build/10091/18), it's available now!), but I've run 3.9.0 locally with no problems. Seems like we should start running in CI as well, since 3.9 is official.

Add python 3.9 testing

---

.travis.yml

fixes #355 
- use the new pip resolver for dependeny installation
- run the docker tests in a separate stage

Fix version incompatibility that breaks twine in docker test

---

.github/workflows/test.yml

Adds an aggregate "tests" job to CI so that we can gate merges on that
without needing to keep merge gates up-to-date with the names of the
various jobs that collectively represent "all tests".
Also dropped the `pull-request` trigger, which I included originally
because I wasn't sure whether the tests on push would run for forks,
which they do!

Add aggregate "tests" job

---

.dockerignore
Dockerfile
docker/docker-requirements.txt
docker/entrypoint.sh
docker/gunicorn.conf.py
docker/test_docker.py
pypiserver/__main__.py
pypiserver/_app.py
pypiserver/backend.py
requirements/test.pip
tests/test_main.py

Updates the Docker configuration to use the gunicorn server with gevent
workers by default. Hopefully this will resolve the symptoms seen when
running pypiserver with the non-production grade wsgiref server as
reported in #286.
Making this happen brought a few other issues to light, which are also
addressed here.
- Docker log output not immediately being flushed to stdout (#358):
resolved by setting the `PYTHONUNBUFFERED` env var to `t` in the
docker container
- When the WSGIRef server is selected, its access logs are written
directly to stderr, rather than going through the logging machinery:
resolved by adding a new `WsgiHandler` class and passing in to
bottle's `run()` method when running the wsgi server. This required a
new `ServerCheck` class to determine whether the wsgi server is …

Gunicorn/gevent docker, log fixes, cache busting

---

.github/workflows/ci.yml
bin/ci_helper.py

Adds a new helper script to determine which docker tags are needed for a
given ref going through CI, and uses those tags to populate the GH
actions matrix for a docker deploy step.
Resolves #373

Push to Docker Hub from CI

---

README.rst

The readme incorrectly specifies `watchdog` as the name of the extra to install. It's actually specified as `cache`. see: https://github.com/pypiserver/pypiserver/blob/df300de33d2ffe01f218396813433f23001dd76b/setup.py#L49

Correct README example

---

contributor_docs/README.md
contributor_docs/architecture_overview.md

This pull request adds a section for the contributor docs and a basic architecture overview as an example.    
Decided to keep the pull request short and maybe, for the starters, just providing a space for adding documentation will give a possibility for others to contribute in parallel :) 
- introduced `./contributor_docs/` folder for extra documentation (inspired by the example of [`p5.js`'s repository structure](https://github.com/processing/p5.js))
- added a `README.md` as an introduction to the docs folder (Should be improved and proofread :))
- added a WIP architecture document (is picked up in a [separate branch](https://github.com/dee-me-tree-or-love/pypiserver/blob/368_update-contributor-docs_first-setup_arch/contributor_docs/architecture_overview.md)) 
- #368

Contributor documentation directory and README

---

.github/workflows/ci.yml

Currently we do not run the GH actions CI/CD pipelines for pull requests from the forked projects although we require passing checks. This MR enables the `pull_request` as an additional trigger for GH Actions (see [docs about it](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-multiple-events-with-activity-types-or-configuration)).
_before_   
_after_  
> (failing mypy check is addressed in #400)
- See below of this Pull Request for the pipeline status
- Related to #400 aimed at fixing the failing `check-types` action

Allow GH actions to run on pull requests for forks

---

.github/workflows/ci.yml
pypiserver/_app.py

The CI pipelines are failing on master on `check types` and `check formatting` steps. 
```plaintext
Run mypy docker/test_docker.py pypiserver/config.py  tests/test_init.py
mypy docker/test_docker.py pypiserver/config.py  tests/test_init.py
shell: /usr/bin/bash -e {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/3.9.6/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.6/x64/lib
pypiserver/config.py:48:1: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.9)
pypiserver/config.py:48:1: note: Hint: "python3 -m pip install types-setuptools"
pypiserver/config.py:48:1: note: (or run "mypy --install-types" to install all missing stub packages)
pypiserver/config.py:48:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found …
```

CI/CD Check fixes

---

.github/workflows/ci.yml
tmp/.notes.txt

As a temporary solution for #406 to unblock the CI/CD on other pull requests.

Temporary disable tests for python3.9

---

pypiserver/_app.py

When using pip >=22, we get the following warning:
"DEPRECATION: The HTML index page being used (https://....) is not a proper
HTML 5 document. This is in violation of PEP 503 which requires these pages
to be well-formed HTML 5 documents. Please reach out to the owners of this
index page, and ask them to update this index page to a valid HTML 5
document. pip 22.2 will enforce this behaviour change. Discussion can be
found at https://github.com/pypa/pip/issues/10825"

Fixed violation of PEP 503 warning with pip>=22

---

pypiserver/_app.py

This ensures compliance with PEP 503
Fixes #412

Specify doctype for generated pages.

---

pypiserver/config.py

Small fix for an issue identified by CI run

fix(typing): fix small typing and lint errors in config.py making CI checks fail

---

.github/workflows/rc.yml
.gitignore
bin/update_changelog.sh

> Related to #405.  
> This is still a work in progress and is likely to change ⚠️ 
To save the time required for creating RC's manually, I'm thinking of delegating this task to GH actions!  
(This should allow me some spare time :D, but also should make the release process more transparent and, hopefully, increase the release frequency) 
Current vision:
1. GH Action `new-rc` will collect all the change information since the latest release.
2. GH Action will prepare an entry in the `CHANGES.rst` under a new _patch_ release candidate.
3. GH Action creates a new branch and a pull request from this branch to the `main` 
4. Maintainers review the proposed release and changes, make manual changes (e.g. to the CHANGES.rst) as necessary, and push upstream
5. Once it's ready, the RC pull request …

chore(release-candidate-from-github-actions): add github action for release management

---

requirements/test.pip
tests/test_server.py

Fixing test setup to overcome https://github.com/pypa/setuptools/issues/3197

fix(setuptools-in-tests): add `packages=[]` in test setup

---

docker/docker-requirements.txt
docker/test_docker.py

Fixes #439. The docker image could not be built due to incompatibility of `gevent==21.1.2` with the newer version of Cython installed as part of the alpine packages during the build. See related releases (21.8.0 and 21.12.0) at <https://www.gevent.org/changelog.html#id1>. 
Example failing workflow ([here](https://github.com/pypiserver/pypiserver/runs/8200700190?check_suite_focus=true#step:6:268))
> ```plaintext
>   Error compiling Cython file:
>   ------------------------------------------------------------
>   ...
>   cdef load_traceback
>   cdef Waiter
>   cdef wait
>   cdef iwait
>   cdef reraise
>   cpdef GEVENT_CONFIG
>         ^
>   ------------------------------------------------------------
>   
>   src/gevent/_gevent_cgreenlet.pxd:182:6: Variables cannot be declared with 'cpdef'. …
```

fix: docker tests in cicd

---

pypiserver/bottle.py

Use `getfullargspec` for Python 3.x to support Python 3.11 where `getargspec` was removed complete.

Replace usage of deprecated inspect.getargspec

---

.github/workflows/ci.yml
tox.ini

Closes #406
Adds Python 3.9, 3.10, and 3.11 release candidate 2 to the testing.
Tox passes on my Mac on both py39 and py310.
@dee-me-tree-or-love Your review, please.

Upgrade GitHub Actions

---

.github/workflows/ci.yml

This PR addresses 2 issues with current CI.
1. The failing tests on Python 3.6 due to `setuptools` being out of date (solution roughly based on https://github.com/docker-library/python/issues/170)
2. Currently, for the central repository PRs, GitHub Actions are running double: on `push` and `pull_request` triggers. 
1. Forcing `setuptools` update before installing `tox`, seems to fix the problem with tests on Python 3.6.
2. Instead of duplicate runs, like #444, the actions are run only once (see this PR checks).
- Before:  
- Now:

fix: force setuptools update + no duplicate runs in GH Actions

---

CHANGES.rst

I forgot to adjust the date for the latest [1.5.1 release](https://github.com/pypiserver/pypiserver/releases/tag/v1.5.1) in `CHANGES.rst`.   
This PR fixes the issue by adding the correct date retrospectively.

fix: correct 1.5.1 tag date in CHANGES

---

README.rst
pypiserver/__init__.py
pypiserver/__main__.py
pypiserver/_app.py
pypiserver/config.py
tests/test_app.py
tests/test_config.py
tests/test_init.py
tests/test_main.py

~~Get the liveness endpoint from the environment variable `HEALTH_ENDPOINT` and verify it. If the customized endpoint is invalied, it will fallback to the DEFAULT_HEALTH_ENDPOINT.~~
UPDATE 2022-10-21
----------------------------
`pypiserver` provides a default health endpoint at `/health`. It always returns
`200 Ok` if the service is up. Otherwise, it means that the service is not responsive.
In addition, `pypiserver` allows users to customize the health endpoint.
Alphanumeric characters, hyphens, forward slashes and underscores are allowed and the endpoint should not overlap with any existing routes.
Valid examples: `/healthz`, `/health/live-1`, `/api_health`, `/action/health`

feat: :stethoscope: allow customized health check endpoint

---

pypiserver/config.py

This solves [a small typing issue](https://github.com/pypiserver/pypiserver/actions/runs/4048433497/jobs/6963668078#step:5:1) in `config.py`:
```bash
...
Run mypy docker/test_docker.py pypiserver/config.py  tests/test_init.py
pypiserver/config.py:692:48: error: Incompatible default for argument "auther" (default has type "None", argument has type "Callable[[str, str], bool]")  [assignment]
...
pypiserver/config.py:831:48: error: Incompatible default for argument "args" (default has type "None", argument has type "Sequence[str]")  [assignment]
...
```
Solved by explicitly declaring it as `t.Optional`.

fix: explicit optional types in `config.py`

---

.github/workflows/ci.yml
requirements/dev.pip

Since the update of `ubuntu-latest` image in [setup-python](https://github.com/actions/setup-python) GitHub Action to `Ubuntu 22.04`, Python 3.6 is no longer available by default. https://github.com/pypiserver/pypiserver/actions/runs/3861663821/jobs/6683883640#step:3:10. See related issue: https://github.com/actions/setup-python/issues/561.  
Since Python 3.6 is declared "end of life" and is planned to be deprecated for `pypiserver 2.0.0`, I believe it's worth disabling these tests. Related to https://github.com/pypiserver/pypiserver/issues/107 and the discussion with @cclauss in https://github.com/pypiserver/pypiserver/pull/447.

chore: disable tests on Python3.6

---

pypiserver/cache.py
pypiserver/config.py
requirements/dev.pip
tests/test_main.py

@dee-me-tree-or-love Your review, please.
Updating https://github.com/psf/black -> 23.1.0.
* https://github.com/psf/black/blob/main/CHANGES.md#2310
> This is the first [psf/black] release of 2023, and following our [stability policy](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy), it comes with a number of improvements to our stable style…

Upgrade to psf/black stable style 2023

---

README.rst

Health endpoint 
README’s `pypi-server run` arguments document is remove by PR #451, and health-endpoint is missing when the `pypi-server run` arguments document bring back in #478

Health endpoint usage is missing.

---

pypiserver/config.py
tests/test_main.py

I prepared a PR which switches default hash-algo to sha256 as discussed in #452. Created as draft PR as it probably should not be merged before major version bump to 2.0 is concrete.
Closes #452

FEAT: Switch default hash-algo to sha256

---

setup.py

[Release of `2.0.0`](https://github.com/pypiserver/pypiserver/releases/tag/v2.0.0) didn't make it to the `PyPi` index [with an error on `long_description`](https://github.com/pypiserver/pypiserver/actions/runs/6370534716/job/17291871269#step:6:26) since it became MD. 
This PR fixes the issue.

fix: specify long_description as MD type

---

.github/workflows/ci.yml
setup.py

Fixing the stale Docker Hub description for `pypiserver/pypiserver`.
It is a known issue and there are a few workarounds suggested here: https://github.com/docker/build-push-action/issues/21

Fix: dockerhub description readme

---

tests/test_pkg_helpers.py

Follow-up for the #536 PR by @doctaweeks 👍 
- Adds a test input with `tar.xz` extension

chore: add tar xz test case

---

.github/workflows/ci.yml
pypiserver/plugin.py
tests/test_init.py

The GH Actions are failing some checks that run on Python `3.x (== 3.12 at the time of writing)`. 
This PR ensures that the last _supported_ Python (in contrast to last _stable_) version is used in the CI/CD. 
- 🏗️ #539 coming up

chore: make the last supported python version explicit in `ci.yaml`

---

.github/workflows/ci.yml
bin/package.sh

Since #539, we use Python 3.12 (`env.LAST_SUPPORTED_PYTHON`) to build distribution archives, but `package.sh` was not updated [overcome the deprecated use of `setup.py` as command line](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/).
This PR offers a fix.
- `package.sh` uses `python -m build` 
- `CI` builds the wheels in any case, but pushes to PyPi only on tags

fix: deprecated `setuptools.py` when building in `package.sh`

---

tests/test_server.py

Fix the `build` calls to use `--no-isolation`, in order to fix regression in running tests in an offline environment.
Unlike the previous `setup.py` calls, `build` defaults to creating a new virtual environment to perform the build.  This, in turn, requires fetching the build dependencies from the Internet, effectively making the tests error out in an offline environment.  Passing `--no-isolation` makes `build` use the already-installed host dependencies instead.

test: Fix running `build` in offline test environment

---

docker-compose.yml

pypiserver compose services were using the deprecated `pypiserver` command instead of `pypiserver run` command.

Update Deprecated Compose Commands for Pypiserver Services

---

.github/workflows/ci.yml
requirements/dev.pip

This PR removes the deprecated `types-pkg_resources` type checking stub.
> [!NOTE]
> <img width="1050" alt="image" src="https://github.com/user-attachments/assets/ed47adf1-64c5-43a2-9ea9-ae8f8b09bc70">

chore: deprecated `types-pkg_resources`

---

Dockerfile

Move to latest alpine image, and later version of python.
This upgrades many packages within the container and fixes many security vulnerabilities.
Python 3.11 fails to build so settled on python 3.10 for now.

Update alpine image to 3.20 and python version to 3.10

---

.github/workflows/ci.yml
.github/workflows/rt.yml

> [!TIP]
> Closes #420 
With the rename to `main` complete, this PR removes the no longer needed references to `master` branch.

chore: finish move to `main`

---

setup.py
tox.ini

We removed the upper bound for `importlib_resources`.
However, this package is required for the temporary support in Python version 3.8-3.12 only (see #539 when it was originally introduced).
- return `importlib_resources` upper bound in `setup.py`
- fix the `envlist` of `tox.ini` to be aligned with `ci.yaml`

fix: use `importlib_resources` only when needed

---

Dockerfile

Adjusted `Dockerfile` syntax based on warnings:
- consistent casing
- `ENV <key>=<value>` syntax

fix: `Dockerfile` syntax warnings

---

README.md
docker/test_docker.py
pypiserver/__main__.py
pypiserver/config.py
tests/test_config.py

> [!TIP]
> For full description see #647.
>
> > Hi,
> > I have added an option to run bottle under a prefix.
> > 
> > All routes are served under // if specified with options --server-base-url PREFIX
>
> -- kudos @skapin : #647
A quick follow-up on the @skapin's nice feature from #647. 
Lint fixes, some testing, and docs.

Feat: integrating prefix server mounting option from #647
