README.rst, pypiserver/__init__.py, pypiserver/_app.py, pypiserver/core.py
=> Auth improvements

pypiserver/__init__.py, pypiserver/_app.py, pypiserver/core.py, tests/test_app.py
=> (2) Add Cache-control header to enable pip caching

README.rst, pypiserver/__init__.py, pypiserver/_app.py, pypiserver/core.py, pypiserver/manage.py
- #81: FIX options are not applied (discovered for logging ones).
- #85: Deterministic package sort-order
- Other maintenance (relative imports, remove line-ending spaces).
=> Merge ##81 & #85

CHANGES.rst, pypiserver/__init__.py
* PEP 008 changes to `__init__.py`
* Updated CHANGES to reflect search addition by @blade2005
=> PEP 008 Changes & Changelog Update

README.rst
Added docs for process management systems `systemd` and `supervisor`
=> Added docs for process management

README.rst
=> Docs for pypi-uploader

README.rst, pypiserver/_app.py, pypiserver/core.py
Also made some RST changes to the docs in general.
=> Removed redundant function, added auther docs

README.rst
=> fixing systemd file typo

README.rst
Added new receipe section for reverse proxy configuration with example configuration for nginx
=> Added receipe for reverse proxy configuration

README.rst, pypiserver/__main__.py, pypiserver/_app.py, tests/test_app.py, tests/test_main.py, tests/test_server.py
This allows multiple users to have differing levels of permissions. In particular, a read-only (list, download) user and a write (upload) user.
I've provided no changes to the documentation as I expect the specific syntax may need to change.
=> Add matrix auth

pypiserver/_app.py
=> Update 404 to match PyPI

docker-compose.yml
Resolves #218 
Thanks @renich!
=> Update compose to version 3.3

README.rst, docker-compose.yml
Fixes things missed in the commit to fix #103
=> Replace .htaccess references with .htpasswd

Dockerfile
Possibly related to secondary symptom in #224
=> Ensured pypiserver user is assoc. w/group

pypiserver/_app.py, pypiserver/bottle.py, pypiserver/core.py, tests/test_app.py, tests/test_core.py
- Improvement of a known limitation.
The limitation is `It does not support changing the prefix of the path of the url (see #155 for workarounds).`
(https://github.com/pypiserver/pypiserver#known-limitations)
- Ref: https://github.com/pypiserver/pypiserver/issues/155
- Changed the links populated by `request.fullpath`. Now it uses `request.url`.
There is an issue behind proxy using nginx with the prefix of the url.
In your code some links are populated with a proxy header `X-Forwarded-Host`.
Here's an example. `request.url` is changed by a proxy header `X-Forwarded-Host`.
https://github.com/pypiserver/pypiserver/blob/537034eb4323f0a84e66cb8d73e3b152c9d08744/pypiserver/_app.py#L92-L93
<br/><br/><br/><br/>
But `request.fullpath` isn't changed by a proxy header. …
=> support changing the prefix of the path of the url

CHANGES.rst, pypiserver/bottle.py
Resolves #257 
This updates our vendored version of Bottle to their most recent release from December of 2019, [0.12.18](https://github.com/bottlepy/bottle/releases/tag/0.12.18). This should resolve the deprecation warnings that were previously being thrown and allow us to officially add python 3.8 support.
=> MAINT: Update bottle to 0.12.18

README.rst, docker-compose.yml
Thanks for this project. I updated the Docker Compose example configuration, so it shows how to setup HTTPS using Traefik.
=> Updated Docker Compose example with HTTPS configuration using Traefik

README.rst
Closes: #307
I gave this a quick first shot. Comments obviously welcome for further tweaking.
=> Slightly clarify the relationship to warehouse.

pypiserver/core.py
=> Fix deprecation warnings due to invalid escape sequences.

pypiserver/__init__.py, pypiserver/__main__.py, pypiserver/_app.py, pypiserver/cache.py, pypiserver/core.py, pypiserver/manage.py, setup.py, tests/doubles.py, tests/test_app.py, tests/test_core.py, tests/test_docs.py, tests/test_main.py, tests/test_server.py
* Remove Python version conditional code
* Remove explicit inheritance from object
* Cleanup setup.py
* Convert most string interpolations to f-strings
* Convert some file io to use pathlib
=> Cleanup code to python 3.6

pypiserver/backend.py, tests/test_server.py
Fixed a couple of complaints by `black` checks on `backend.py` and `test_server.py`
=> fix(small-black-format-fixes): small styling fixes

README.rst
The README.rst was not updated for a while. Adding a new contact point + explicit call for new maintainers!
=> chore(new-people-readme): adjust maintainers & add call for new people

bootstrap.py
https://portingguide.readthedocs.io/en/latest/builtins.html#moved-reload
=> from importlib import reload for Python 3

README.rst
Current README is slightly outdated. I updated it to use the `run` and `update` command where appropriate
=> Update README to reflect run/update commands

README.rst, pypiserver/config.py
Add note that the units of `--Cache-Control` is seconds.
=> Update README.rst and config.py

.github/workflows/rt.yml
Making the release-preparations slightly simpler.
- no CHANGES check
- support dry-run mode
=> chore: simpler release_tag action

.github/workflows/ci.yml
For addressing #468 
Only added arm64 + amd64 in that I have built and tested them locally and everything seemed to work fine.
Happy to add more archs if needed
=> Bump github action versions and add multiarch support

pypiserver/_app.py
Made a small change to the HTML formatting and tested locally to verify the deprecation warning is now gone.
This should resolve #580
=>  Updated HTML formatting (#580)

pypiserver/manage.py
This replaces the XML-RPC mechanism (which is deprecated and heavily rate-limited, as documented at
https://warehouse.pypa.io/api-reference/xml-rpc.html) with the simple JSON API (PEP 691, https://peps.python.org/pep-0691/).
This is a minimalistic implementation with almost no error handling, but in this context it should behave about the same as the old XML-RPC code (which also had almost no error handling). No additional packages are required, and it should work without issues from Python 3.6 through 3.11 (tested on 3.10)
This should resolve issues #392 and #388.
=> Use simple JSON API to get package releases.

README.md
This PR makes small adjustments to the README:
- GitHub handlers instead of direct email and name.
- Added @pawamoy to the list, thanks for all the help in managing issues and discussions lately! 🌟 
- Small decorations with `note` and `tip` callouts.
- Tiny spelling checks and typography edits.
=> chore: cleanup README

.github/workflows/ci.yml, .github/workflows/rc.yml, .github/workflows/rt.yml, README.md, bin/ci_helper.py
This PR prepares for the change from `master` to `main`: #420
=> chore: prepare for renaming to main

README.md
- Fixed badges
- Improving some code snippets
- Paragraph restructure
- Some more callouts
=> chore: brush up some `README` content
